return {
    Tabs = {
        "تنظیمات منو",
        "شخصیت",
        "خودرو",
        "هدف گيري",
        "چيت هاي ويژه",
        "(ESP) وال هک",
        "اطلاعات سازنده"
    },
    GuiTexts = {
        MainPanelTitle = "Privete Menu By Shadow",
        OwnerTitle = "مجموعه:",
        DeveloperTitle = "طراح و نويسنده:",
        TelegramTitle = "کانال تلگرام:",
        YoutubeTitle = "کانال یوتیوب:",
        KeyName = "فعلی",
        KeySettingsHeader = "تنظیمات کلید منو و میانبرها",
        OpenCloseKeySetting = "تنظیم کلید باز و بسته کردن منو:",
        PressAnyKey = "یک کلید را فشار دهید...",
        KeyPrefix = "کليد ",
        KeyChangeHint = "براي تغيير کليد روي دکمه بالا کليک کنيد",
        IncreaseHealth = "افزایش سلامتی",
        IncreaseArmor = "افزایش زره",
        Suicide = "خودکشی",
        ReSpawn = "ري اسپاون",
        Teleport = "تلپورت",
        Unfreeze = "رفع انجماد",
        WeaponHack = "هک اسلحه",
        FakeSkin = "اسکین جعلی",
        GetJetpack = "دريافت جت پک",
        GiveWanted = "وانتد دادن",
        SpeedRun = "افزایش سرعت دویدن",
        FlyHack = "پرواز",
        GodMode = "جان بي نهايت",
        Attention = "توجه",
        InfinityOxygen = "نفس بي نهايت",
        InfinityRun = "دويدن بي نهايت",
        Invisible = "نامرئی",
        AutoCBug = "سي باگ خودکار",
        RapidFire = "شلیک سریع",
        AntiGreenZone = "شليک در گرين زون",
        AirBrake = "اير بريک",
        TrollFoot = "پرتاب بازيکن ها در حالتي که پياده هستيد",
        TrollOnMsg = "چيت روشن شد نزديک بازيکن هاي مد نظر شيد",
        RepairCar = "تعمیر خودرو",
        Nitro = "نیتروژن",
        UnfreezeCar = "رفع انجماد خودرو",
        FlipCar = "صاف کردن خودرو",
        SpawnCar = "اسپاون ماشين",
        EjectCar = "اجکت ماشين",
        CarGodMode = "گاد مود",
        AutoFlip = "صاف کردن خودکار",
        CarSpeedHack = "افزایش سرعت خودرو",
        CarFlyHack = "پرواز",
        AntiBikeFall = "عدم سقوط از موتور موقع تصادف",
        InfinityFuel = "بنزين نا محدود و روشن ماندن خودرو",
        DriveAllCars = "سوار شدن به همه ماشين هاي فکشن",
        TrollCar = "پرتاب بازيکن ها وقتي سوار ماشين هستيد",
        LockAimBot = "قفل هدف گيري )هنگام شليک(",
        SilentAimBot = "سايلنت ايم بات",
        Settings = "تنظیمات",
        SpecNotification = "اعلان تماشاگر )اسپکت فايندر(",
        OnlineNotification = "ديدن ليست ادمين هاي آنلاين",
        TeleportJobBot = "جاب بات مخصوص شعل هايي",
        CheckPointHint = "که چک پوينت قرمز دارن مثل چوب بري",
        PrisonBreak = "خروج و فرار از زندان",
        FishingBot = "ربات ماهیگیری",
        RpGodMode = "Rp گاد مود مخصوص سرور هاي",
        TwoDBoxESP = "جعبه دو بعدي",
        ThreeDBoxESP = "جعبه سه بعدي",
        LineESP = "وال هک خطي",
        AimingESP = "محل شليک",
        ObjectFinderID = "آبجکت فايندر با آيدي",
        WeaponHackTitle = "هک اسلحه",
        WeaponIDInput = "شناسه اسلحه",
        BulletAmountInput = "تعداد گلوله",
        SubmitWeapon = "ثبت اسلحه",
        CloseBtn = "بستن",
        FakeSkinTitle = "اسکین جعلی",
        SkinIDInput = "شناسه اسکین",
        SubmitSkin = "ثبت اسکین",
        GiveWantedTitle = "دادن وانتد به بازيکنا )فيک کيل(",
        PlayerIDInput = "آيدي بازيکن",
        FakeKillBtn = "فيک کيل",
        SpeedRunTitle = "افزایش سرعت دویدن",
        SpeedAmount = "مقدار سرعت",
        SpawnCarTitle = "اسپاون ماشين",
        CarIDInput = "آيدي ماشين",
        SpawnCarBtn = "اسپاون ماشين",
        EjectCarTitle = "تلپورت و سوار شدن به ماشين",
        CommandLabel = ": کامند",
        CommandDL = "/DL",
        CommandHint = "بزنيد تا آيدي ماشين هارو با رنگ آبي ببينيد",
        EjectCarBtn = "تلپورت و سوار شدن به ماشين",
        SpecSettingTitle = "تنظیمات اعلان تماشاگر",
        SpecHint1 = "در اين بخش بايد تگ رو تنظيم کنيد که",
        SpecHint2 = "فقط چه اشخاصي و مقامي که اسپکت شما ميشه رو نشون بده",
        TagAdmin = "[A] مدیر",
        TagHelper = "[H] هلپر",
        TagVip = "[V] بازیکن وي اي پي",
        TagNormal = "بازيکن هاي بدون تگ مثل هاستر",
        CloseSettingsBtn = "بستن تنظيمات",
        ObjectFinderTitle = "پيدا کردن آبجکت با آيديش",
        ObjectHint1 = "در اين بخش با وارد کردن آيدي آبجکت",
        ObjectHint2 = "ميتوانيد آبجکت مورد نظرتون رو پيدا کنين",
        ObjectIDInput = "آيدي آبجکت",
        FindObjectCheck = "پيدا کردن آبجکت"
    }
}
